networks:
  grafana-monitoring:
    driver: bridge

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - "127.0.0.1:14318:4318" # OTLP HTTP
      - "127.0.0.1:9464:9464" # Prometheus metrics
      - "127.0.0.1:13133:13133" # Health check
    volumes:
      - ./otel/otel-collector.yml:/etc/otel-collector.yml:ro
    command: ["--config=/etc/otel-collector.yml"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana-monitoring

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./loki/data:/loki/data
      - ./loki/loki-config.yml:/etc/loki/config.yml:ro
    command: -config.file=/etc/loki/config.yml
    user: "0:0"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana-monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus/data"
      - "--storage.tsdb.retention.time=7d"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana-monitoring

  tempo:
    image: grafana/tempo
    container_name: tempo
    restart: unless-stopped
    ports:
      - "127.0.0.1:3200:3200"
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml:ro
      - ./tempo/data:/var/tempo
    command: ["-config.file=/etc/tempo.yml"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3200/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana-monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/data:/var/lib/grafana/data
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana-monitoring
